### ISSUE TITLE
Slack signup not working

### ISSUE THREAD

**Issue by andysylvester** [scripting/feedlandSupport#106]
I tried to join the Slack group using Google (got a page with a question from the Wayback Machine), then tried using my email address directly (entered the code, got a message from Slack that the code was not vaild).

**Comment by scripting** [comment]
Try this link. It expires after 24 hours.

https://join.slack.com/t/feedland/shared_invite/zt-1hz9zxulz-zYSGZHD1KCOW1uwPBYjkCA

**Comment by akaKenSmith** [comment]
That link worked for me just now, thanks.

**Comment by andysylvester** [comment]
That link worked for me as well - thanks! 

Even though I am watching this repo, I did not get any notifications of this issue thread. Just reporting....

**Comment by scripting** [comment]
These are the confusing instructions for how to sign up for a slack group that's public.

https://slack.com/help/articles/205239967-Join-a-channel

But there is a tip...

> Tip: If you know the name of the channel you'd like to join, you can type /join followed by # and the channel name in the message field and send the message.

So that might be..

http://feedland.slack.com/join#supporting-new-feedland-users

Someone who hasn't joined the group yet might try that and see if it works.

**Comment by scripting** [comment]
Here's a link that theoretically never expires.

https://join.slack.com/t/feedland/shared_invite/zt-1hz9zxulz-zYSGZHD1KCOW1uwPBYjkCA

**Comment by andysylvester** [comment]
Closing this issue, there seems to be a reliable way to join the Slack group.
