### ISSUE TITLE
The getting started popup comes up every time I load the page.

### ISSUE THREAD

**Issue by offbyone** [scripting/feedlandSupport#118]
<img width="710" alt="image" src="https://user-images.githubusercontent.com/181693/198888648-a3dca0ff-db83-4ca6-a423-02c11c47d343.png">

I see that every time I refresh [my own username](http://feedland.org/?username=offby1) or go to the index (which redirects to my page).

**Comment by scripting** [comment]
@offbyone -- sorry for the annoying dialog. the way it's programmed now -- it comes up if you are subscribed to less than 10 feeds. you are subscribed to 6. so the simplest workaround is to subscribe to 3 more feeds and it'll stop bothering you.

i could make it a one time thing, probably should -- but i'd hate to see someone get lost just because they didn't click OK the first time.

**Comment by scripting** [comment]
@offbyone -- don't add the feeds. i'm going to change the software. give me a few minutes. :smile:

**Comment by scripting** [comment]
@offbyone -- i made the change. here's how it should work now.

you will see the dialog one more time. 

after that you should never see it again.

for a new user (not you, you're already on board) they will only see it once.

**Comment by offbyone** [comment]
The dialog is gone, but also so are the six feeds I _was_ following.

**Comment by scripting** [comment]
I think we solved the problem here, whatever else was going on i can't imagine it was caused or related to this minor fix. I'm going to close the issue.
